### ISSUE TITLE
Stop monsters from generating on top of each other

### ISSUE THREAD

**Issue by cmcollander** [cmcollander/CompSciGUI#34]

**Comment by rafeykhan** [comment]
has someone already fixed this? the code seems to incorporate the check for monsters

**Comment by cawetzel** [comment]
The monster generator should already check, but I think the problem was during the "run" of the predator prey the monsters sometimes converged on one spot causing all to move as a group.

**Comment by rafeykhan** [comment]
oh okay.that makes sense

**Comment by cmcollander** [comment]
This should be fixed, so I'll mark it closed unless something else comes up during our bug checks
