### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by rafeykhan** [cmcollander/CompSciGUI#55]
1) should the ships be allowed to move towards the docks if there are no monsters generated? (in predator prey)
2) is it possible for the ship models to be oriented correctly in 3D i.e. all facing towards the docks?
3) if a ship goes into a wrong dock and is X'd out, or if two ships collide and are X'd out, should the ships be removed from the arraylist? just like the oil spill, we can put something there aswell. ( I know it will be over-complicating things, but there is no way of telling which ships are unsafe during the simulation?

**Comment by cmcollander** [comment]
1. Sounds like a good idea for the ships to not worry about docks if there
   are no monsters.
2. This would be fairly easy to do. We can just set the ship direction to
   the inverse tangent of dy/dx and divide by (pi/2). I'll work on this
   tonight.
3. The map class has a is ship safe function you can call from the 3d
   model. Just don't know what we can do on the 3d model to indicate an unsafe
   ship.
